import type { Metadata } from "next";
import { EB_Garamond, IBM_Plex_Mono} from "next/font/google";
import "./globals.css";

const gara = EB_Garamond({ subsets: ["latin"] ,
variable: '--font-gara',
});
const ibm = IBM_Plex_Mono({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-ibm',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gara.className} ${ibm.variable}`}>{children}</body>
    </html>
  );
}
